/**
 * 基底 主架構 不要亂改
 * Next.js 的主架構（Root Layout）。
 * 
 * 最外層的佈局組件 (根佈局)
 * 所有頁面的共同容器 前台,後台,login
 * 設定全域配置的地方
 * 此處保持乾淨，只做必要的設定
 * 因為是 server component，所以不能使用 client-side 的 hooks
 */

import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import QueryClientProvider from "@/providers/query-client-provider"
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import NextTopLoader from 'nextjs-toploader';
import Overlay from '@/components/Overlay';

// 1. 設定字體
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. SEO metadata（會套用到所有頁面）
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>; // 注意：最新版 Next.js params 是 Promise
}) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Provider 讓 Client Components 也能用翻譯 */}
        <NextIntlClientProvider messages={messages}>
            <QueryClientProvider> {/* 全域的 React Query 設定 */}
              {/* <Overlay/> */}
              <NextTopLoader 
                color="#2299DD"
                  initialPosition={0.08}
                  crawlSpeed={200}
                  height={3}
                  crawl={true}
                  showSpinner={true}
                  easing="ease"
                  speed={200}
                  shadow="0 0 10px #2299DD,0 0 5px #2299DD"
                  template='<div class="bar" role="bar"><div class="peg"></div></div> 
                  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
                  zIndex={1600}
                  showAtBottom={false}/>
             {children} {/* 所有頁面內容都會渲染在這裡 */}
              <Toaster />
          </QueryClientProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}



// 3. Root Layout - 主架構 server component 
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//           <QueryClientProvider> {/* 全域的 React Query 設定 */}
//             {children} {/* 所有頁面內容都會渲染在這裡 */}
//           </QueryClientProvider>
//       </body>
//     </html>
//   );
// }
